---
abstract: 'Guitar tab image generator.'
author:
  - 'Koichi Taniguchi <taniguchi@livedoor.jp>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: GD-Tab-Guitar
no_index:
  directory:
    - inc
    - t
requires:
  Class::Accessor::Fast: 0
  GD: 2.3
  List::Util: 0
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.03
